name: Push ONNX from Snowflake Stage to Repo (CLI)

on:
  workflow_dispatch:   # allows manual trigger from GitHub Actions tab

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Snowflake CLI
      run: |
        pip install snowflake-cli-labs

    - name: Configure Snowflake CLI
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      run: |
        mkdir -p ~/.snowflake
        cat <<EOF > ~/.snowflake/config.toml
        [connections.default]
        account = "${SNOWFLAKE_ACCOUNT}"
        user = "${SNOWFLAKE_USER}"
        password = "${SNOWFLAKE_PASSWORD}"
        role = "${SNOWFLAKE_ROLE}"
        warehouse = "${SNOWFLAKE_WAREHOUSE}"
        database = "${SNOWFLAKE_DATABASE}"
        schema = "${SNOWFLAKE_SCHEMA}"
        EOF

    - name: Download ONNX file from Snowflake Stage
      run: |
        mkdir -p staged_models
        snow sql -q "GET @MY_ONNX_STAGE/coat_lite_tiny_Opset16.onnx file://staged_models/"

    - name: Commit and push model file
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add staged_models/coat_lite_tiny_Opset16.onnx
        git commit -m "Update ONNX model from Snowflake stage" || echo "No changes to commit"
        git push
