name: Push ONNX from Snowflake Stage to Repo

on:
  workflow_dispatch:   # allows manual trigger from GitHub Actions tab

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Snowflake connector
      run: |
        pip install "snowflake-snowpark-python[pandas]"

    - name: Download ONNX file from Snowflake stage
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      run: |
        python - << 'EOF'
        import os
        from snowflake.snowpark import Session

        conn_params = {
            "account": os.environ["SNOWFLAKE_ACCOUNT"],
            "user": os.environ["SNOWFLAKE_USER"],
            "password": os.environ["SNOWFLAKE_PASSWORD"],
            "role": os.environ["SNOWFLAKE_ROLE"],
            "warehouse": os.environ["SNOWFLAKE_WAREHOUSE"],
            "database": os.environ["SNOWFLAKE_DATABASE"],
            "schema": os.environ["SNOWFLAKE_SCHEMA"],
        }

        session = Session.builder.configs(conn_params).create()

        # Download ONNX from stage to local runner
        session.file.get("@MY_ONNX_STAGE/coat_lite_tiny_Opset16.onnx", "./staged_models")

        print("✅ Model downloaded to ./staged_models/")
        session.close()
        EOF

    - name: Commit and push model file
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add staged_models/coat_lite_tiny_Opset16.onnx
        git commit -m "Update ONNX model from Snowflake stage"
        git push
